function presets = ColorKit_UserPresets()
% ColorKit_UserPresets  User-added presets generated by ColorKit.
%
% Author: zhaoyh, 2026.
% Email: zhao2025@mail.sustech.edu.cn
%
% Edit metadata fields here if needed. Default values are "none".

rows = cell(0, 9);
% <ColorKit_USER_PRESETS_BEGIN>
rows(end + 1, :) = {"My_Color_1", "Custom", "none", ["#95AFAD" "#BBCAE7" "#E5F7F6" "#FFF7C8" "#FFC5AC" "#FF8064"], "plot_line", "none", "none", "none", "none"};
rows(end + 1, :) = {"My_Color_2", "Custom", "none", ["#F9FBFD" "#F4F9FD" "#EEF8FD" "#E9F6FD" "#E4F4FD" "#DFF2FD" "#DAEFFD" "#D5EDFC" "#D0EAFC" "#CAE8FC" "#C5E6FC" "#BEE4FC" "#B9E2FC" "#B4E0FC" "#AEDEFC" "#A9DBFB" "#A4D9FA" "#9ED7FA" "#98D4FA" "#91D1FA" "#8CCFFA" "#8ACEFA" "#8DCFF3" "#94D2E2" "#9DD6CD" "#A6DAB7" "#AFDDA5" "#B8E192" "#C1E57F" "#CBE96C" "#D4ED57" "#DFF23F" "#ECF823" "#F4FC12" "#F8FB0B" "#FBF406" "#FDE803" "#FFDA01" "#FFCE00" "#FFC100" "#FFB300" "#FFA500" "#FF9700" "#FF8A00" "#FF7C00" "#FE6E00" "#FE6100" "#FE5300" "#FE4500" "#FE3800" "#FF2B00" "#FE2000" "#F91400" "#EE0700" "#E40100" "#D60000" "#BE0202" "#A10505" "#8B0909" "#861010" "#902C2C" "#A75E5E" "#CA9F9F" "#F8E9E9"], "FJ_Spectrum", "none", "none", "none", "none"};
% <ColorKit_USER_PRESETS_END>

presets = struct('name', {}, 'category', {}, 'type', {}, 'anchors', {}, ...
    'recommendedUse', {}, 'isColorblindFriendly', {}, 'isPrintFriendly', {}, ...
    'centerColor', {}, 'sourceStyle', {}, 'matlabName', {}, 'nativeN', {});
if isempty(rows)
    return
end
presetTemplate = struct('name', "", 'category', "", 'type', "", 'anchors', strings(1, 0), ...
    'recommendedUse', "", 'isColorblindFriendly', "", 'isPrintFriendly', "", ...
    'centerColor', "", 'sourceStyle', "", 'matlabName', "", 'nativeN', []);
presets(1, size(rows, 1)) = presetTemplate;
for k = 1:size(rows, 1)
    presets(k) = struct('name', string(rows{k, 1}), ...
        'category', string(rows{k, 2}), 'type', string(rows{k, 3}), ...
        'anchors', string(rows{k, 4}), 'recommendedUse', string(rows{k, 5}), ...
        'isColorblindFriendly', string(rows{k, 6}), ...
        'isPrintFriendly', string(rows{k, 7}), 'centerColor', string(rows{k, 8}), ...
        'sourceStyle', string(rows{k, 9}), 'matlabName', "", 'nativeN', []);
end
end

